# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 构建分支
        required: false
        default: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: 检出代码
      uses: actions/checkout@v3
      with: 
        ref: master
      
    - name: 安装 node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: 构建
      run: yarn && npm run build
    
    - name: 发布pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        cp -r .git dist/ && cd dist
        git checkout --orphan gh-pages
        git add .
        git commit -m "publish pages"
        git push --force --progress "origin" gh-pages
